.Dd $Mdocdate: May 19 2021 $
.Dt jsonkv 1
.Os
.Sh NAME
.Nm jsonkv
.Nd convert JSON files to a simple key-value format
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm jsonkv
is a simple command-line tool for converting JSON files to a simple
key-value format, so that JSON content can be easily processed with
standard line-based Unix text-processing tools such as grep, sed, awk.
.Sh EXAMPLES
Show the body of all a-tags that are under body-tags, that are under
html-tags:
.Pp
.Dl $ jsonkv <users.json | grep users/user/name
.Sh SEE ALSO
.Xr xmlkv 1
